import cv2
originalImage = cv2.imread('man_moon.png')
grayImage = cv2.imread('man_moon.png',0)
#grayimage2 = cv2.imread('man_moon.png', cv2.IMREAD_GRAYSCALE)
#grayImage_Convert = cv2.cvtColor(originalImage, cv2.COLOR_BGR2GRAY)
thresholder = int(input("Input the threshold: "))
(thresh, blackAndWhiteImage) = cv2.threshold(grayImage, thresholder, 255, cv2.THRESH_BINARY)
cv2.imshow('Black white image1', blackAndWhiteImage)
cv2.imshow('Original image', originalImage)
#cv2.imshow('gray image', grayImage)
#cv2.imshow('gray image2', grayimage2)
#cv2.imshow('gray image3', grayImage_Convert)
cv2.waitKey(0)
cv2.destroyAllWindows()